---
- name: Play to execute a command
  hosts: junos
  roles:
    - Juniper.junos
  tasks:
  - juniper_junos_facts:
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
    register: facts

  - debug: var=facts
    run_once: true


