---
- name: Play to execute a command
  hosts: vMX3
  tasks:
  - name: show OSPF neigbor 
    junos_command:
        commands: show ospf neighbor
        #display: xml 
    register: junos_output

  - debug: var=junos_output


