---
- name: Play to execute a command
  hosts: vMX2
  tasks:
  - name: Execute XML RPC Call 
    junos_command:
        rpcs:
         - get-ospf-neighbor-information
    register: junos_output

  - debug: var=junos_output




