---
- name: Play to execute a command
  hosts: iosxr
  connection: local
  gather_facts: no
  tasks:
  - name: get all interfaces
    iosxr_command:
        commands:
         - show interfaces
    register: iosxr_output

  - name: parse output
    set_fact: iosxr_intf={{iosxr_output.stdout[0]|parse_cli_textfsm('../ntc_templ/cisco_xr_show_interfaces.template')}}
  - set_fact: iosxr_intf_lst={{iosxr_intf|map(attribute='INTERFACE')|list}}

  - file: path=intf_output.txt state=absent
  - file: path=intf_output.txt state=touch
  - name: save all output to file
    template:
      src: intf_template.j2
      dest: ./intf_output.txt

