---
- name: Play to execute a command
  hosts: ios
  connection: local
  gather_facts: no
  vars:
    interfaces:
      - f0/0
      - f1/0
    #  - f2/0
  tasks:
  - name: show version on IOS
    ios_command:
        commands:
         - show interface {{item}}
    register: ios_output
    with_items: "{{interfaces}}"
#  - debug: var=ios_output

  - name: check interface status
    assert: 
      msg: "{{inventory_hostname}} {{item.item}} is down"
      that: "'line protocol is up' in item.stdout[0]"
    with_items: "{{ios_output.results}}"
    ignore_errors: true

  - name: log interface status
    lineinfile: 
      path: ./log_output.txt
      regexp: "{{inventory_hostname}}"
      line: "{{inventory_hostname}}, {{item.item}} is down"
    when: "not ('line protocol is up' in item.stdout[0])"
    with_items: "{{ios_output.results}}"