---
- name: Test When
  hosts: all
  tasks:
  - name: Run for JunOS only
    debug: 
     msg: "All Run ok for {{inventory_hostname}}"
    when: "'junos' in hostvars[inventory_hostname].group_names"


