---
- name: Play to execute a command
  hosts: ios
  connection: local
  gather_facts: no
  tasks:
  - name: Get OSPF Neigbors
    ios_command:
        commands:
         - sh ip ospf  neighbor
    register: ospf_output

  - debug: var=ospf_output

