---
## First Play
- hosts: localhost
  name: Create node data model
  tags: [ model ]
  vars_files:
  - "{{model|default('intf_lld.yml')}}"
  tasks:
  - name: Create per-node data model (NMP) from LLD data model
    template: src=lld_to_nmp.j2 dest=./intf_NMP.yml

## Second Play
- name: Generate Configuration for all routers
  gather_facts: no
  connection: local
  hosts: all
  tags: [ template ]
  tasks:
    - include_vars: "./intf_NMP.yml"
    - file: path=intf-config  state=directory
      run_once: true
    - name: Generate Device Configuration
      template: src=./conf_template/{{dev_os}}-core.j2 dest=intf-config/{{inventory_hostname}}-intf.txt

## Third Play
- name: Configure Nodes
  hosts: all
  tags: [ deploy ]
  tasks:
    - name: Create Diff Directory
      file: path=diff state=directory
      run_once: true

    - name: Push conifguration on all Nodes
      napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        dev_os: "{{dev_os}}"
        password: "{{ ansible_ssh_pass }}"
        config_file: ./intf-config/{{inventory_hostname}}-intf.txt
        commit_changes: "{{commit| default('no')}}"
        diff_file: diff/{{inventory_hostname}}-diff.txt
