---
- name: Execute show commands on IOS
  hosts: ios
  #connection: local
  #gather_facts: no
  tasks:
  - name: show version on IOS
    ios_command:
        commands:
         - show version
         
  - name: debug output
    debug: var=vars

- name: Execute show commands on JunOS
  hosts: junos
  #connection: local
  #gather_facts: no
  tasks:
  - name: show version on JunOS
    junos_command:
        commands:
        - show version

