---
- name: Play to execute a command
  hosts: ios
  connection: local
  gather_facts: no
  tasks:
  - name: show version on IOS
    ios_facts:
    register: ios_facts

  - name: debug IOS facts
    debug: var=ios_facts
