---
- name: Play to execute a command
  hosts: ios
  connection: local
  gather_facts: no
  vars:
    commands:
     - {name: show_route, cmd: show ip route}
     - {name: show_arp, cmd: show arp}
  tasks:
  - name: show version on IOS
    ios_command:
        commands:
        - "{{item.cmd}}"
    register: ios_output
    with_items: "{{commands}}"

  - name: save the output
    blockinfile:
     path: ./{{inventory_hostname}}_results.txt
     block: |
       "{{item.stdout[0]}}"
     marker: "########### Output ########"
     create: yes
    with_items: "{{ios_output.results}}"
  
  - name: print output
    debug: var=ios_output

