---
- name: Play to execute a command
  hosts: ios
  connection: local
  gather_facts: no
  tasks:
  - name: show version on IOS
    ios_command:
        commands:
         - show version
    register: ios_output

  - name: copy output to file
    copy:
     content: |
       ######## show version ######## 
       {{ios_output.stdout[0]}}
     dest: ./show_version.txt
  - name: print output
    debug: var=vars
