---
## First Play
- hosts: localhost
  name: Create node data model
  gather_facts: no
  tags: [ model ]
  vars_files:
  - "{{model|default('core-model.yml')}}"
  tasks:
  - name: Create per-node data model from Topology data model
    template: src=core-to-nodes.j2 dest=./nodes.yml

## Second Play
- name: Generate Configuration for all routers
  gather_facts: no
  connection: local
  hosts: all
  tags: [ template ]
  tasks:
    - include_vars: "./nodes.yml"
    - file: path=core-config  state=directory
      run_once: true
    - name: Generate Core Configuration
      template: src=./conf-template/{{dev_os}}-core.j2 dest=core-config/{{inventory_hostname}}-core.txt