---
- name: GET NAPALM Facts
  hosts: all
  tasks:
  - name: GET BGP Peers
    napalm_get_facts:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      dev_os: "{{dev_os}}"
      password: "{{ ansible_ssh_pass }}"
      filter: 
        - interfaces_ip

  - debug: var=napalm_interfaces_ip

  - name: Create output file
    template:
      src: intf_report.j2
      dest: ./{{inventory_hostname}}_intf.csv
