---
- name: Play to execute a command
  hosts: junos
  tasks:

  - name: Get show printout
    junos_command:
      commands: 
      - show ospf neighbor 
    register: show_output

  - debug: var=hostvars
    run_once: true

  - name: Create output file
    template:
      src: template_single_file_v1.j2
      dest: ./output_per_router_v1/{{inventory_hostname}}.txt




