---
- name: Play to execute a command
  hosts: junos
  tasks:

  - name: Get show printout
    junos_command:
      commands: 
      - show ospf neighbor 
    register: show_output

  - debug: var=show_output

  - name: Create Folder for output collection
    file: path=output_per_router_v1 state=directory
    run_once: yes

  - name: Create output file
    template:
      src: template_single_file_v1.j2
      dest: ./output_per_router_v1/{{inventory_hostname}}.txt

  - assemble:
      src: ./output_per_router_v1
      dest: ./ospf_output_final.txt
    run_once: yes

  - name: Delete Folder for output collection
    file: path=output_per_router_v1 state=absent
    run_once: yes



