---
- name: Create configuration template
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - debug: var=vars
    #run_once: true

  - blockinfile:
      block: "{{ vars|to_nice_yaml(indent=4)}}"
      marker: "### {mark} ######"
      dest: "./{{inventory_hostname}}-vars.txt"
      create: yes
    run_once: true

  # - name: create  configuration template
  #   template:
  #    src: templates/{{os}}/initial.j2
  #    dest: configs/{{inventory_hostname}}.txt

  # - name: create folder for configuration
  #   file:
  #    path=configs state=directory
  #   run_once: true

