---
- name: Play to execute a command
  hosts: junos
  tasks:

  - name: Get OSPF neigbors
    junos_command:
        commands:
         - show ospf neighbor
        display: xml
    register: ospf_output

  - set_fact: 
     ospf_peers: "{{ospf_output.output[0]['rpc-reply']['ospf-neighbor-information']['ospf-neighbor']}}"

  - debug: var=vars
  - file: path=ospf_output state=directory
    run_once: yes

  - template:
      src: ./ospf_report.j2
      dest: ospf_output/ospf_report-{{inventory_hostname}}.csv
      
  - assemble:
      src: ospf_output
      dest: ./ospf_output.final


