- hosts: localhost
  connection: local
  gather_facts: no
  vars: 
    prefix1: 10.1.1.0/24 # prefix 
    prefix2: 10.1.1.1/24 # IP address with subnet
    prefix3: 10.1.1.1
  tasks:
    - debug:
          msg: " is a Vlaid Address {{prefix2|ipaddr}}"  

    - name: Get IP address from Prefix (remove prefix)
      debug:
          msg: "ip address is {{prefix1|ipaddr('network')}} 
                prefix is {{prefix1|ipaddr('netmask')}}"

    - name: Get IP address from IP/prefix (remove prefix)
      debug:
          msg: "ip address is {{prefix2|ipaddr('address')}} 
                prefix is {{prefix1|ipaddr('prefix')}}"

    - name: Get 1st IP from IP Prefix
      debug:
          msg: |
                ip address with prefix {{prefix1|ipaddr(1)}}
                ip address without prefix is {{prefix1|ipaddr(1)|ipaddr('address')}} 
                prefix is {{prefix1|ipaddr('prefix')}}

    - name: Get 1st IP from IP address with subnet
      debug:
          msg: |
                ip address with prefix {{prefix2|ipaddr(2)}} 
                ip address without prefix is {{prefix2|ipaddr(2)|ipaddr('address')}} 
                prefix is {{prefix1|ipaddr('prefix')}}