---
- name: Test Loops
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
   interfaces:
    f0/0: {vlan: 10, ip: 192.10.1.1/24}
    f0/1: {vlan: 20, ip: 192.10.2.1/24}
  tasks:
  - debug:   
     msg: "set interface {{item.key}} unit {{item.value.vlan}} address {{item.value.ip}}"
    with_dict: "{{interfaces}}"
