---
- name: Play to execute a command
  hosts: ios
  connection: local
  gather_facts: no
  serial: 1
  vars:
    domain: stc.lab.com
  tasks:
  - name: save the output
    blockinfile:
     path: results-{{inventory_hostname}}.txt
     block: |
      !
      hostname {{inventory_hostname}}
      ip domain name {{domain}}
      !  
     create: yes
     backup: yes
