---
- name: Play to execute a command
  hosts: ios
  connection: local
  gather_facts: no
  serial: 1
  vars:
    interfaces:
      - {name: FastEthernet3/0, vlan: 10, prefix: 192.168.10.0/24}
      - {name: FastEthernet4/0, vlan: 20, prefix: 192.168.20.0/24}
  tasks:
  - name: save the output
    blockinfile:
     path: int_conf-{{inventory_hostname}}.txt
     block: |
      !
      interface {{item.name}}.{{item.vlan}}
       encapsulation dot1Q {{item.vlan}}
       ip address {{item.prefix|ipv4('1')}} 
      ! 
     marker: "! ### {mark} {{item.name}} "
     create: yes
    with_items: "{{interfaces}}"

